const base=COIN_DATA,references=COIN_REFERENCES,key="alex-coins-v1",$=x=>document.querySelector(x),ds=["All","5¢","10¢","25¢","$1","$2"];
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let owned=CoinCollection.read(),denom="All",miss=false,coloured=false,q="";
const isColoured=c=>/^colour\b/i.test(c.variant);
function save(){if(!CoinCollection.save(owned))$('#saveStatus').textContent='Browser storage is unavailable. Changes will last for this visit only.';}
function cropStyle(im){if(!im.crop)return '';const [x,y,w,h,W,H]=im.crop;return `--crop-ratio:${w}/${h};--image-width:${W/w*100}%;--image-height:${H/h*100}%;--image-left:${-x/w*100}%;--image-top:${-y/h*100}%`;}
function photoMarkup(c,im,title){const img=`<img class="coinPhoto" src="${im.image}?v=20261008a" alt="${title}" loading="lazy" decoding="async">`;return im.crop?`<span class="coinCrop" style="${cropStyle(im)}">${img}</span>`:img;}
function visual(c){const im=COIN_IMAGES[c.id],title=escapeHTML(`${c.year} · ${c.name} · ${c.variant}`);
 return im.image?`<button class="visual photoButton" data-photo="${c.id}" aria-label="Enlarge ${title}"><span class="tag">${c.denomination}</span>${photoMarkup(c,im,title)}</button>`:`<a class="visual sourceFallback" href="${escapeHTML(im.sourcePage)}" target="_blank" rel="noopener noreferrer" aria-label="View ${title} at source"><span class="tag">${c.denomination}</span><span>View exact variant<br>at source ↗<small>Exact photo pending verification</small></span></a>`;
}
function render(){let h=base.filter(c=>owned[c.id]).length,p=Math.round(h/base.length*100);$('#overall').textContent=`${h} / ${base.length} · ${p}%`;$('#overallBar').style.width=p+'%';
 $('#filters').innerHTML=ds.map(d=>`<button data-d="${d}" aria-pressed="${d===denom}" class="${d===denom?'active':''}">${d}</button>`).join('');document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{denom=b.dataset.d;render()});$('#missingBtn').classList.toggle('active',miss);$('#missingBtn').setAttribute('aria-pressed',miss);$('#colouredBtn').classList.toggle('active',coloured);$('#colouredBtn').setAttribute('aria-pressed',coloured);
 $('#stats').innerHTML=ds.slice(1).map(d=>{let a=base.filter(c=>c.denomination===d),x=a.filter(c=>owned[c.id]).length;return `<div class="stat"><b>${d} · ${x}/${a.length}</b><small>${Math.round(x/a.length*100)}% collected</small></div>`}).join('');
 let a=base.filter(c=>(denom==='All'||c.denomination===denom)&&(!miss||!owned[c.id])&&(!coloured||isColoured(c))&&(`${c.year} ${c.name} ${c.variant} ${c.series}`.toLowerCase().includes(q)));$('#resultCount').textContent=`Showing ${a.length} ${a.length===1?'coin':'coins'}`;
 const referenceCards=references.filter(c=>!miss&&!coloured&&(denom==='All'||c.denomination===denom)&&(`${c.name} ${c.denomination} standard reference`.toLowerCase().includes(q))).map(c=>`<article class="card reference">${visual(c)}<div class="body"><div class="meta"><span>${c.denomination}</span><span>REFERENCE</span></div><h3>${escapeHTML(c.name)}</h3><div class="variant">${escapeHTML(c.variant)}</div><small class="sourceNote">${escapeHTML(c.series)}</small><a class="imageSource" href="${COIN_IMAGES[c.id].sourcePage}" target="_blank" rel="noopener noreferrer">Image source: Royal Canadian Mint ↗</a><a class="storyLink" href="coin.html?id=${c.id}">Read the story →</a></div></article>`).join('');
 $('#grid').innerHTML=(referenceCards+a.map(c=>{const im=COIN_IMAGES[c.id];return `<article class="card ${owned[c.id]?'owned':'missing'}">${visual(c)}<div class="body"><div class="meta"><span>${c.year}</span><span>${owned[c.id]?'COLLECTED':'MISSING'}</span></div><h3>${escapeHTML(c.name)}</h3><div class="variant">${escapeHTML(c.variant)}</div><div class="series">${escapeHTML(c.series)}</div><a class="imageSource" href="${escapeHTML(im.sourcePage)}" target="_blank" rel="noopener noreferrer">${im.image?'Image':'Reference'} source: ${escapeHTML(im.credit)} ↗</a>${im.licenseUrl?`<a class="imageSource" href="${escapeHTML(im.licenseUrl)}" target="_blank" rel="noopener noreferrer">${escapeHTML(im.license)}</a>`:''}${im.note?`<small class="sourceNote">${escapeHTML(im.note)}</small>`:''}<a class="storyLink" href="coin.html?id=${c.id}">Read the story →</a><button class="check" data-id="${c.id}" aria-pressed="${!!owned[c.id]}">${owned[c.id]?'✓ In my collection':'+ Add to collection'}</button></div></article>`;}).join(''))||'<p class="empty">No coins match your filters.</p>';
 document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{owned[b.dataset.id]=!owned[b.dataset.id];save();render();document.querySelector(`[data-id="${b.dataset.id}"]`)?.focus();});
 document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>openPhoto(b.dataset.photo));
 document.querySelectorAll('.coinPhoto').forEach(img=>img.onerror=()=>{const button=img.closest('[data-photo]'),im=COIN_IMAGES[button.dataset.photo];const a=document.createElement('a');a.className='visual sourceFallback';a.href=im.sourcePage;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Image unavailable · View at source ↗';button.replaceWith(a);});
}
function openPhoto(id){const c=[...base,...references].find(c=>String(c.id)===String(id)),im=COIN_IMAGES[id];$('#photoTitle').textContent=`${c.year} · ${c.name}`;$('#photoVariant').textContent=`${c.denomination} · ${c.variant}`;$('#photoFrame').className=im.crop?'cropped':'';$('#photoFrame').setAttribute('style',cropStyle(im));$('#largePhoto').src=im.image+'?v=20261008a';$('#largePhoto').alt=`${c.year} ${c.name} ${c.variant}`;$('#photoSource').href=im.sourcePage;$('#photoSource').textContent=`Image source: ${im.credit} ↗`;$('#photoVariant').textContent+=im.status==='design-reference'?' · Photo: colour version':'';$('#photoStory').href='coin.html?id='+encodeURIComponent(c.id);$('#photoDialog').showModal();}
$('#closePhoto').onclick=()=>$('#photoDialog').close();$('#photoDialog').onclick=e=>{if(e.target===$('#photoDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('#search').oninput=e=>{q=e.target.value.toLowerCase();render();};$('#search').setAttribute('aria-label','Search coin, year or series');$('#missingBtn').onclick=()=>{miss=!miss;render();};$('#colouredBtn').onclick=()=>{coloured=!coloured;render();};render();

$('#randomCoin').onclick=()=>CoinCollection.openRandom();
window.addEventListener('pageshow',()=>{owned=CoinCollection.read();render();});
window.addEventListener('storage',e=>{if(e.key===key){owned=CoinCollection.read();render();}});
