const base=COIN_DATA,key="alex-coins-v1",$=x=>document.querySelector(x),ds=["All","5¢","10¢","25¢","$1","$2"];
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let stored=null;
try { stored=JSON.parse(localStorage.getItem(key)||'null'); } catch {}
// Merge the erroneous 2005 Lucky Loonie entry into its correct 2006 ID.
if(stored?.owned?.[110]===true){stored.owned[112]=true;}
let owned=Object.fromEntries(base.map(c=>[c.id,typeof stored?.owned?.[c.id]==='boolean'?stored.owned[c.id]:c.owned])),denom="All",miss=false,coloured=false,q="";
const isColoured=c=>/^colour\b/i.test(c.variant);
function save(){try{localStorage.setItem(key,JSON.stringify({owned}));}catch{$('#saveStatus').textContent='Browser storage is unavailable. Changes will last for this visit only.';}}
function visual(c){const im=COIN_IMAGES[c.id],title=escapeHTML(`${c.year} · ${c.name} · ${c.variant}`);
 return im.image?`<button class="visual photoButton" data-photo="${c.id}" aria-label="Enlarge ${title}"><span class="tag">${c.denomination}</span><img class="coinPhoto" src="${im.image}?v=20261007c" alt="${title}" loading="lazy" decoding="async"></button>`:`<a class="visual sourceFallback" href="${escapeHTML(im.sourcePage)}" target="_blank" rel="noopener noreferrer" aria-label="View ${title} at source"><span class="tag">${c.denomination}</span><span>View exact variant<br>at source ↗<small>Exact photo pending verification</small></span></a>`;
}
function render(){let h=base.filter(c=>owned[c.id]).length,p=Math.round(h/base.length*100);$('#overall').textContent=`${h} / ${base.length} · ${p}%`;$('#overallBar').style.width=p+'%';
 $('#filters').innerHTML=ds.map(d=>`<button data-d="${d}" aria-pressed="${d===denom}" class="${d===denom?'active':''}">${d}</button>`).join('');document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{denom=b.dataset.d;render()});$('#missingBtn').classList.toggle('active',miss);$('#missingBtn').setAttribute('aria-pressed',miss);$('#colouredBtn').classList.toggle('active',coloured);$('#colouredBtn').setAttribute('aria-pressed',coloured);
 $('#stats').innerHTML=ds.slice(1).map(d=>{let a=base.filter(c=>c.denomination===d),x=a.filter(c=>owned[c.id]).length;return `<div class="stat"><b>${d} · ${x}/${a.length}</b><small>${Math.round(x/a.length*100)}% collected</small></div>`}).join('');
 let a=base.filter(c=>(denom==='All'||c.denomination===denom)&&(!miss||!owned[c.id])&&(!coloured||isColoured(c))&&(`${c.year} ${c.name} ${c.variant} ${c.series}`.toLowerCase().includes(q)));$('#resultCount').textContent=`Showing ${a.length} ${a.length===1?'coin':'coins'}`;
 $('#grid').innerHTML=a.map(c=>{const im=COIN_IMAGES[c.id];return `<article class="card ${owned[c.id]?'owned':'missing'}">${visual(c)}<div class="body"><div class="meta"><span>${c.year}</span><span>${owned[c.id]?'COLLECTED':'MISSING'}</span></div><h3>${escapeHTML(c.name)}</h3><div class="variant">${escapeHTML(c.variant)}</div><div class="series">${escapeHTML(c.series)}</div><a class="imageSource" href="${escapeHTML(im.sourcePage)}" target="_blank" rel="noopener noreferrer">${im.image?'Image':'Reference'} source: ${escapeHTML(im.credit)} ↗</a>${im.licenseUrl?`<a class="imageSource" href="${escapeHTML(im.licenseUrl)}" target="_blank" rel="noopener noreferrer">${escapeHTML(im.license)}</a>`:''}${im.note?`<small class="sourceNote">${escapeHTML(im.note)}</small>`:''}<button class="check" data-id="${c.id}" aria-pressed="${!!owned[c.id]}">${owned[c.id]?'✓ In my collection':'+ Add to collection'}</button></div></article>`;}).join('')||'<p class="empty">No coins match your filters.</p>';
 document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{owned[b.dataset.id]=!owned[b.dataset.id];save();render();document.querySelector(`[data-id="${b.dataset.id}"]`)?.focus();});
 document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>openPhoto(Number(b.dataset.photo)));
 document.querySelectorAll('.coinPhoto').forEach(img=>img.onerror=()=>{const c=base.find(c=>c.id===Number(img.parentElement.dataset.photo)),im=COIN_IMAGES[c.id];const a=document.createElement('a');a.className='visual sourceFallback';a.href=im.sourcePage;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Image unavailable · View at source ↗';img.parentElement.replaceWith(a);});
}
function openPhoto(id){const c=base.find(c=>c.id===id),im=COIN_IMAGES[id];$('#photoTitle').textContent=`${c.year} · ${c.name}`;$('#photoVariant').textContent=`${c.denomination} · ${c.variant}`;$('#largePhoto').src=im.image+'?v=20261007c';$('#largePhoto').alt=`${c.year} ${c.name} ${c.variant}`;$('#photoSource').href=im.sourcePage;$('#photoSource').textContent=`Image source: ${im.credit} ↗`;$('#photoVariant').textContent+=im.status==='design-reference'?' · Photo: colour version':'';$('#photoDialog').showModal();}
$('#closePhoto').onclick=()=>$('#photoDialog').close();$('#photoDialog').onclick=e=>{if(e.target===$('#photoDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('#search').oninput=e=>{q=e.target.value.toLowerCase();render();};$('#search').setAttribute('aria-label','Search coin, year or series');$('#missingBtn').onclick=()=>{miss=!miss;render();};$('#colouredBtn').onclick=()=>{coloured=!coloured;render();};render();
